# Domyslna ustawienie wlaczenia pluginu.
# Zawsze mozesz go wlaczyc lub wylaczyc komenda /anti-bot status <enable|disable>
enabled: true
# Lokalizacja folderu z graczami
file-directory: './plugins/Anti-Bot/players'
# Ustawienia rodzajow ochrony
options:
  # Rejestracja kont
  accounts: true
  # Blokowanie chatowych komend, definiujesz ich liste w `block-cmd-list`.
  block-cmd: true
# Wiadomosc do gracza przy stworzeniu konta w `accounts`
# Zmienne:
#     $player - nick gracza,
#     $hostname - nazwa hosta,
#     $uuid - UUID gracza,
#     $ip - IP gracza
kick-message:
- '&&aTwoje konto zostalo pomyslnie utworzone.'
- '&&aProsimy, zaloguj sie ponownie na nasz serwer!'
# Lista zablokowanych komend w `block-cmd`
block-cmd-list:
- '!attackall'
- '!attack'
- '!build'
- '!calc'
- '!derp'
- '!destroy'
- '!drop'
- '!dropall'
- '!equip'
- '!follow'
- '!help'
- '!say'
- '!spam'
- '!stop'
- '!status'
- '!tool'
block-cmd-message: '&&cNie mozesz uzywac komend od bot√≥w!'
